### ISSUE TITLE
Set up Python Streamlit app for Codespaces

### ISSUE THREAD

**Issue by Alberto-Codes** [Alberto-Codes/Transcript_Recipe#1]
## Description
We want to create a Streamlit app that can be developed collaboratively using GitHub Codespaces in the cloud. 

## Requirements

- Python 3.7+
- Latest Streamlit 
- Codespaces access and connectivity

## Tasks  

- [ ] Initialize Python virtual environment
- [ ] Install Streamlit  
- [ ] Create "Hello World" Streamlit example  
- [ ] Initialize Git repo
- [ ] Set up Codespace config
- [ ] Test launching Codespace and running app
- [ ] Add README with dev instructions 

## Out of Scope 

- Deployment to production 
- Complex CI/CD pipelines
- Authentication
- Scalability / reliability 

## Goal

Collaboratively develop Streamlit app in cloud using Codespaces.

## Links

[Streamlit documentation](https://docs.streamlit.io)
[Codespaces Docs](https://docs.github.com/en/codespaces)
